name: user_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  authentication_client:
    path: ../authentication_client/authentication_client
  database_client:
    path: ../database_client
  flutter:
    sdk: flutter
  powersync_repository:
    path: ../powersync_repository
  rxdart: ^0.28.0
  shared:
    path: ../shared

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0
