name: instagram_clone_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  animations: ^2.1.1
  api_repository:
    path: packages/api_repository
  app_ui:
    path: packages/app_ui
  authentication_client:
    path: packages/authentication_client/authentication_client
  bloc: ^9.0.1
  env:
    path: packages/env
  equatable: ^2.0.8
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_gen: any
  flutter_localizations:
    sdk: flutter
  form_fields:
    path: packages/form_fields
  get_it: ^9.2.0
  google_sign_in: ^7.2.0
  instagram_blocks_ui:
    path: packages/instagram_blocks_ui
  intl: ^0.20.2
  powersync_repository:
    path: packages/powersync_repository
  shared:
    path: packages/shared
  supabase: ^2.10.2
  supabase_authentication_client:
    path: packages/authentication_client/supabase_authentication_client
  supabase_flutter: ^2.12.0
  token_storage:
    path: packages/authentication_client/token_storage
  user_repository:
    path: packages/user_repository
dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
