name: instagram_blocks_ui
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  app_ui:
    path: ../app_ui
  flutter:
    sdk: flutter
  shared:
    path: ../shared  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
