name: powersync_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  env:
    path: "../env"
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.5
  powersync: ^1.17.0
  shared:
    path: "../shared"
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
